name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26.2"

      # 3. Run backend test
      - name: Run post-service tests
        working-directory: ./services/post-service
        run: go test ./...

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ================= AUTH =================
      - name: Build auth image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/peoplespost_microservices-auth-service ./services/auth-service

      - name: Push auth image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/peoplespost_microservices-auth-service

      # ================= AI =================
      - name: Build ai image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/peoplespost_microservices-ai-service ./services/ai-service

      - name: Push ai image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/peoplespost_microservices-ai-service

      # ================= POSTS =================
      - name: Build posts image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/peoplespost_microservices-posts-service ./services/post-service

      - name: Push posts image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/peoplespost_microservices-posts-service

      # ================= GATEWAY =================
      - name: Build gateway image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/peoplespost_microservices-api-gateway ./services/api-gateway

      - name: Push gateway image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/peoplespost_microservices-api-gateway

      # ================= FRONTEND =================
      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/peoplespost_microservices-frontend ./peoplepostF

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/peoplespost_microservices-frontend
